--- #YAML:1.0
name:               Algorithm-Diff-Fast
version:            0.01
abstract:           Efficiently compute differences between files / lists
author:
    - Stuart Watt <stuart@morungos.com>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::Deep:  0
    Test::More:  0
requires:
    perl:        5.010000
    Test::Deep:  0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
